Description: "Notebook Instance to be used for Lookout Vision Workshop"
Resources:
  MyS3Bucket:
      Type: AWS::S3::Bucket
  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.m4.xlarge"
      RoleArn: !GetAtt ExecutionRole.Arn
      VolumeSizeInGB: 10
      DefaultCodeRepository: "https://github.com/jayrao/LFVDemo.git"
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "LFV"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "lookoutvision:*"
                Resource: "*"
Outputs:
  BasicNotebookInstanceId:
    Value: !Ref BasicNotebookInstance